title: "Lander - Rife Design - Apollo13 Premium WordPress Theme"
email: "vidhyav656@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
 ‘Lander’ is one of many Landing Page demos included in the Rife Free WordPress Theme. The free version features AJAX loading portfolio items, video backgrounds, intro typewriter effect text, a sticky header that smooth scrolls to sections, testimonials, pricing table, team, a contact form and WooCommerce + Elementor support. One of the better free WordPress themes I’ve seen in the past couple years!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techtab.github.io/Lander/" # the base hostname & protocol for your site, e.g. http://example.com
facebook_url: https://www.facebook.com/#/
twitter_url: https://twitter.com/#
linkedin_url: https://www.linkedin.com/company/#/
# github_url:  https://github.com
# pinterest_url: https://www.pinterest.com/
# instagram_url: https://www.instagram.com/
logo: "/assets/img/logos/.png"
cover_image: "/assets/img/bg/page-title.jpg"

permalink: "/:title/"

#set incremental to true in order to speed up build time. When using set post and pages to 'regenerate: true'

incremental: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      #author_profile: false
      regenerate: true
  # assets
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "/images"
    values:
      image: true
  - scope:
      path: "/pdfs"
    values:
      pdf: true

#collections
collections:
  features:
    output: true
  services:
    output: true

compress_html:
  comments: ["<!-- ", " -->"]

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  jekyll-archives:
  enabled: category
  layouts:
    category: category
  permalinks:
    category: '/category/:name/'

feed:
      path: "/feed.xml"

exclude:
  - .jekyll-cache
